//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRFuture.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonalInfoArabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalInfoArabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRFuture.Resources.PersonalInfoArabic", typeof(PersonalInfoArabic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string applydate {
            get {
                return ResourceManager.GetString("applydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string bdate {
            get {
                return ResourceManager.GetString("bdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأخوة.
        /// </summary>
        public static string bronum {
            get {
                return ResourceManager.GetString("bronum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الحالي.
        /// </summary>
        public static string curraddres {
            get {
                return ResourceManager.GetString("curraddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة التعليمة.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string educationbranch {
            get {
                return ResourceManager.GetString("educationbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم باللغة الانكليزية.
        /// </summary>
        public static string ename {
            get {
                return ResourceManager.GetString("ename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأب.
        /// </summary>
        public static string fathername {
            get {
                return ResourceManager.GetString("fathername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظارات.
        /// </summary>
        public static string glass {
            get {
                return ResourceManager.GetString("glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتعاني من مشاكل صحية.
        /// </summary>
        public static string health {
            get {
                return ResourceManager.GetString("health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة (الهوية/دفتر العائلة).
        /// </summary>
        public static string idphoto {
            get {
                return ResourceManager.GetString("idphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string isactive {
            get {
                return ResourceManager.GetString("isactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصديق.
        /// </summary>
        public static string knownfriend {
            get {
                return ResourceManager.GetString("knownfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة غراس.
        /// </summary>
        public static string knowngheraspage {
            get {
                return ResourceManager.GetString("knowngheraspage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المبادرة.
        /// </summary>
        public static string knowninitiative {
            get {
                return ResourceManager.GetString("knowninitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان السابق.
        /// </summary>
        public static string lastaddress {
            get {
                return ResourceManager.GetString("lastaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية.
        /// </summary>
        public static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم.
        /// </summary>
        public static string mothername {
            get {
                return ResourceManager.GetString("mothername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتستخدم الانترنت.
        /// </summary>
        public static string netifuse {
            get {
                return ResourceManager.GetString("netifuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجال استخدام الانترنت.
        /// </summary>
        public static string netusing {
            get {
                return ResourceManager.GetString("netusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        public static string personalphoto {
            get {
                return ResourceManager.GetString("personalphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف الأرضي.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدرسة.
        /// </summary>
        public static string schoolname {
            get {
                return ResourceManager.GetString("schoolname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس الجاكيت.
        /// </summary>
        public static string sizejacket {
            get {
                return ResourceManager.GetString("sizejacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس البنطال.
        /// </summary>
        public static string sizepants {
            get {
                return ResourceManager.GetString("sizepants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس الكنزة.
        /// </summary>
        public static string sizeshirt {
            get {
                return ResourceManager.GetString("sizeshirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس الحذاء.
        /// </summary>
        public static string sizeshoes {
            get {
                return ResourceManager.GetString("sizeshoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس الطقم الرياضي.
        /// </summary>
        public static string sizesport {
            get {
                return ResourceManager.GetString("sizesport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس الفيست.
        /// </summary>
        public static string sizevest {
            get {
                return ResourceManager.GetString("sizevest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدخين.
        /// </summary>
        public static string smoke {
            get {
                return ResourceManager.GetString("smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التدخين.
        /// </summary>
        public static string smoketype {
            get {
                return ResourceManager.GetString("smoketype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدوام.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        public static string updateddate {
            get {
                return ResourceManager.GetString("updateddate", resourceCulture);
            }
        }
    }
}
