//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRFuture.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personal_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_Info()
        {
            this.Best_Friends = new HashSet<Best_Friends>();
            this.Emergency_Address = new HashSet<Emergency_Address>();
            this.Other_Course = new HashSet<Other_Course>();
            this.Personal_Skills = new HashSet<Personal_Skills>();
        }

        public int id { get; set; }
        public string type { get; set; }
        [Display(Name = "fname", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string fname { get; set; }
        [Display(Name = "lname", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string lname { get; set; }
        [Display(Name = "fathername", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string fathername { get; set; }
        [Display(Name = "mothername", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string mothername { get; set; }
        [Display(Name = "ename", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string ename { get; set; }
        [Display(Name = "bdate", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public Nullable<System.DateTime> bdate { get; set; }
        [Display(Name = "bronum", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public Nullable<int> bronum { get; set; }
        [Display(Name = "glass", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public bool glass { get; set; }
        [Display(Name = "smoke", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public bool smoke { get; set; }
        [Display(Name = "health", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public bool health { get; set; }
        [Display(Name = "smoketype", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string smoketype { get; set; }
        [Display(Name = "curraddres", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string curraddres { get; set; }
        [Display(Name = "lastaddress", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string lastaddress { get; set; }
        [Display(Name = "mobile", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string mobile { get; set; }
        [Display(Name = "phone", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string phone { get; set; }
        [Display(Name = "mail", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string mail { get; set; }
        [Display(Name = "facebook", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string facebook { get; set; }
        [Display(Name = "education", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string education { get; set; }
        [Display(Name = "netifuse", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public bool netifuse { get; set; }
        [Display(Name = "netusing", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string netusing { get; set; }
        [Display(Name = "notes", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string notes { get; set; }
        [Display(Name = "knownfriend", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string knownfriend { get; set; }
        [Display(Name = "knowninitiative", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string knowninitiative { get; set; }
        [Display(Name = "knowngheraspage", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public bool knowngheraspage { get; set; }
        [Display(Name = "applydate", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public Nullable<System.DateTime> applydate { get; set; }
        [Display(Name = "sizejacket", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string sizejacket { get; set; }
        [Display(Name = "sizeshirt", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string sizeshirt { get; set; }
        [Display(Name = "sizepants", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public Nullable<int> sizepants { get; set; }
        [Display(Name = "sizevest", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string sizevest { get; set; }

        [Display(Name = "sizesport", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string sizesport { get; set; }
        [Display(Name = "sizeshoes", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public Nullable<int> sizeshoes { get; set; }
        [Display(Name = "isactive", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public bool isactive { get; set; }
        [Display(Name = "personalphoto", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string personalphoto { get; set; }
        [Display(Name = "idphoto", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string idphoto { get; set; }
        [Display(Name = "schoolname", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string schoolname { get; set; }
        [Display(Name = "Time", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string Time { get; set; }
        [Display(Name = "updateddate", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public Nullable<System.DateTime> updateddate { get; set; }
        [Display(Name = "educationbranch", ResourceType = typeof(Resources.PersonalInfoArabic))]
        public string educationbranch { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Best_Friends> Best_Friends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergency_Address> Emergency_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Other_Course> Other_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal_Skills> Personal_Skills { get; set; }
    }
}
