//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skills_Info()
        {
            this.Personal_Skills = new HashSet<Personal_Skills>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal_Skills> Personal_Skills { get; set; }
    }
}
